SELECT COUNT(*) INTO @TrangThaiYeuCauExists
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'YEUCAUDANGKY'
    AND COLUMN_NAME = 'TrangThaiYeuCau';

SET @sql = IF(
        @TrangThaiYeuCauExists = 0,
        'ALTER TABLE YEUCAUDANGKY ADD COLUMN TrangThaiYeuCau VARCHAR(30) NOT NULL DEFAULT ''Yeu cau moi''',
        'SELECT 1'
);

PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT COUNT(*) INTO @NgayTaoExists
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'YEUCAUDANGKY'
    AND COLUMN_NAME = 'NgayTao';

SET @sql2 = IF(
        @NgayTaoExists = 0,
        'ALTER TABLE YEUCAUDANGKY ADD COLUMN NgayTao DATE',
        'SELECT 1'
);

PREPARE stmt2 FROM @sql2;
EXECUTE stmt2;
DEALLOCATE PREPARE stmt2;